name: ci + cd demo workflow

# define when the workflow should run/ On a push to main, a PR to main or manually with workflow

on:
  push:
    branches: [ march30 ]
  pull_request:
    branches: [ march30 ]
  workflow_dispatch: 
  
jobs:
  Install-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: |
            /home/runner/work/DevOps-P4/DevOps-P4/
            !/home/runner/work/DevOps-P4/DevOps-P4/node_modules
            !/home/runner/work/DevOps-P4/DevOps-P4/.git
    

  Install-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - run: npm install


  Test-linux:
    runs-on: ubuntu-latest
    needs: [ Install-linux ]
    steps:
    - run: chmod 777 -R /home/runner/work/DevOps-P4/DevOps-P4/
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: /home/runner/work/DevOps-P4/DevOps-P4/
    - run: npm test


  Test-windows:
    runs-on: windows-latest
    needs: [ Install-windows ]
    steps:
    - run: npm test